command: ["streamlit", "run", "app/app.py", "--server.port=8080"]

env:
  - name: "LAKEBASE_SECRET_SCOPE"
    value: "job_copilot"
  - name: "LAKEBASE_SECRET_KEY"
    value: "lakebase-url"
  - name: "DATABRICKS_HOST"
    valueFrom: "databricks_host_secret"
  - name: "DATABRICKS_TOKEN"
    valueFrom: "databricks_token_secret"