"""
Direct Vector Access embedding ingestion for job_documents.

This script implements a Direct Vector Access pattern, storing embeddings
directly in Lakebase (Postgres with pgvector) WITHOUT using Databricks
Vector Search or automatic Delta table synchronization.

Pipeline:
1. Read job_copilot.job_documents rows that do not yet have embeddings for the
   current content_hash.
2. Deduplicate documents by document_id before processing.
3. Chunk description_text using a sliding window:
      CHUNK_SIZE = 800
      CHUNK_OVERLAP = 100
4. Embed each chunk using:
      sentence-transformers/all-MiniLM-L6-v2
   producing 384-dimensional vectors.
5. Batch-upsert embeddings into job_copilot.job_embeddings using psycopg2 and pgvector.

Important database schema:

job_copilot.job_documents
    id              TEXT

job_copilot.job_embeddings
    id              BIGINT          -- generated by PostgreSQL
    document_id     TEXT            -- FK -> job_documents.id
    source_type
    chunk_index
    chunk_text
    content_hash
    embedding       VECTOR(384)
    model_name

The embedding table has a UNIQUE constraint on:

    (document_id, chunk_index)

Therefore the PostgreSQL-generated BIGINT `id` is intentionally NOT supplied
by this script.

The upsert uses:

    ON CONFLICT (document_id, chunk_index) DO UPDATE

This makes re-runs idempotent.

Run directly:

    python ingest_job_embeddings.py

Optional:

    python ingest_job_embeddings.py --batch-size 500
"""

import argparse
import logging
import sys
from typing import Optional

import psycopg

from app.lakebase import get_connection


# ---------------------------------------------------------------------------
# Schema Setup
# ---------------------------------------------------------------------------

def ensure_job_schema():
    """
    Ensure the required Lakebase tables exist.

    sql/lakebase_schema.sql is the source of truth for this schema (tables
    9-10, job_documents and job_embeddings). This function is a redundant,
    idempotent safety net for standalone runs -- CREATE TABLE IF NOT EXISTS
    is a no-op if lakebase_schema.sql already ran.
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            # Ensure pgvector extension is available
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector")

            # Create job_copilot.job_documents table
            cur.execute("""
                CREATE TABLE IF NOT EXISTS job_copilot.job_documents (
                    id TEXT PRIMARY KEY,
                    source_type TEXT NOT NULL,
                    description_text TEXT,
                    content_hash TEXT NOT NULL,
                    created_at TIMESTAMPTZ DEFAULT now()
                )
            """)

            # Create job_copilot.job_embeddings table with pgvector extension
            cur.execute("""
                CREATE TABLE IF NOT EXISTS job_copilot.job_embeddings (
                    id BIGSERIAL PRIMARY KEY,
                    document_id TEXT NOT NULL REFERENCES job_copilot.job_documents(id) ON DELETE CASCADE,
                    source_type TEXT NOT NULL,
                    chunk_index INTEGER NOT NULL,
                    chunk_text TEXT NOT NULL,
                    content_hash TEXT NOT NULL,
                    embedding VECTOR(384) NOT NULL,
                    model_name TEXT NOT NULL,
                    created_at TIMESTAMPTZ DEFAULT now(),
                    UNIQUE (document_id, chunk_index)
                )
            """)

            # Create index on document_id for faster lookups
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_job_embeddings_document_id
                ON job_copilot.job_embeddings(document_id)
            """)

            # Create index on content_hash for faster existence checks
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_job_embeddings_content_hash
                ON job_copilot.job_embeddings(content_hash)
            """)

        conn.commit()

    logger.info("Database schema verified/created successfully.")


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

EMBEDDING_DIM = 384

DEFAULT_CHUNK_SIZE = 800
DEFAULT_CHUNK_OVERLAP = 100

DEFAULT_BATCH_SIZE = 500


# ---------------------------------------------------------------------------
# SQL
# ---------------------------------------------------------------------------

# A document needs embedding when there is no embedding row for the same
# document_id + current content_hash.
#
# This handles:
#   1. Documents that have never been embedded (new job postings/profiles).
#   2. Documents whose description_text/content_hash changed (e.g. a
#      posting was edited, or the profile/resume was updated).
#
# We intentionally do NOT use job_embeddings.id here because that
# column is a PostgreSQL-generated BIGINT primary key.

FETCH_UNEMBEDDED_SQL = """
SELECT
    d.id,
    d.source_type,
    d.description_text,
    d.content_hash
FROM job_copilot.job_documents AS d
WHERE d.description_text IS NOT NULL
  AND length(trim(d.description_text)) > 0
  AND NOT EXISTS (
      SELECT 1
      FROM job_copilot.job_embeddings AS e
      WHERE e.document_id = d.id
        AND e.content_hash = d.content_hash
  );
"""


# IMPORTANT:
#
# `id` is intentionally omitted.
#
# PostgreSQL generates job_embeddings.id automatically.
#
# The existing UNIQUE constraint:
#
#     job_embeddings_document_id_chunk_index_key
#
# is used for idempotent upsert.

UPSERT_EMBEDDINGS_SQL = """
INSERT INTO job_copilot.job_embeddings
(
    document_id,
    source_type,
    chunk_index,
    chunk_text,
    content_hash,
    embedding,
    model_name
)
VALUES (%s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (document_id, chunk_index)
DO UPDATE SET
    source_type = EXCLUDED.source_type,
    chunk_text = EXCLUDED.chunk_text,
    content_hash = EXCLUDED.content_hash,
    embedding = EXCLUDED.embedding,
    model_name = EXCLUDED.model_name,
    created_at = now();
"""


# Column order MUST match the INSERT list above:
#
# document_id,
# source_type,
# chunk_index,
# chunk_text,
# content_hash,
# embedding,
# model_name


# ---------------------------------------------------------------------------
# Chunking
# ---------------------------------------------------------------------------

def chunk_text(
    text: str,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
    overlap: int = DEFAULT_CHUNK_OVERLAP,
) -> list[str]:
    """
    Split text into overlapping sliding-window chunks.

    Example:

        chunk_size = 800
        overlap = 100

    The next chunk starts 700 characters after the previous chunk.

    A document shorter than chunk_size becomes one chunk.
    """

    if chunk_size <= 0:
        raise ValueError("chunk_size must be greater than 0")

    if overlap < 0:
        raise ValueError("chunk_overlap cannot be negative")

    if overlap >= chunk_size:
        raise ValueError(
            "chunk_overlap must be smaller than chunk_size"
        )

    text = text.strip()

    if not text:
        return []

    if len(text) <= chunk_size:
        return [text]

    step = chunk_size - overlap

    chunks = []

    for start in range(0, len(text), step):

        chunk = text[start:start + chunk_size].strip()

        if chunk:
            chunks.append(chunk)

        if start + chunk_size >= len(text):
            break

    return chunks


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

def fetch_unembedded_documents(cur) -> list[dict]:
    """
    Fetch job documents that need a new/current embedding.

    lakebase.get_connection() already configures the connection with
    psycopg2.extras.RealDictCursor, so cur.fetchall() already returns
    dict-like rows (RealDictRow, which subclasses dict) keyed by column
    name -- there is no need to (and must not) manually zip(columns, row):
    zip() against a dict iterates its KEYS, not its values, which silently
    replaces every field's value with its own column name as a string.
    That is a classic cause of a ForeignKeyViolation -- doc["id"] would
    evaluate to the literal string "id" rather than a real document id.
    """

    cur.execute(FETCH_UNEMBEDDED_SQL)

    return [dict(row) for row in cur.fetchall()]


# ---------------------------------------------------------------------------
# Embedding model
# ---------------------------------------------------------------------------

_model = None
_model_name_loaded: Optional[str] = None


def get_model(
    model_name: str = DEFAULT_MODEL_NAME,
):
    """
    Lazily load the SentenceTransformer model once per process.
    """

    global _model
    global _model_name_loaded

    if _model is None or _model_name_loaded != model_name:

        from sentence_transformers import SentenceTransformer

        logger.info(
            "Loading embedding model: %s",
            model_name,
        )

        _model = SentenceTransformer(model_name)

        _model_name_loaded = model_name

    return _model


def embed_chunks(
    chunks: list[str],
    model_name: str = DEFAULT_MODEL_NAME,
) -> list[list[float]]:
    """
    Generate normalized embeddings for a list of text chunks.
    """

    if not chunks:
        return []

    model = get_model(model_name)

    vectors = model.encode(
        chunks,
        show_progress_bar=False,
        normalize_embeddings=True,
    )

    result = [
        vector.tolist()
        for vector in vectors
    ]

    # Safety check:
    # sentence-transformers/all-MiniLM-L6-v2 must produce 384 dimensions.

    for index, vector in enumerate(result):

        if len(vector) != EMBEDDING_DIM:

            raise ValueError(
                f"Embedding dimension mismatch at chunk {index}: "
                f"expected {EMBEDDING_DIM}, got {len(vector)}"
            )

    return result


# ---------------------------------------------------------------------------
# Main ingestion
# ---------------------------------------------------------------------------

def run(
    batch_size: int = DEFAULT_BATCH_SIZE,
    model_name: str = DEFAULT_MODEL_NAME,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
    chunk_overlap: int = DEFAULT_CHUNK_OVERLAP,
) -> int:
    """
    Full embedding ingestion pass.

    Steps:
        1. Fetch documents needing embeddings.
        2. Deduplicate documents by document_id.
        3. Chunk document text.
        4. Generate embeddings.
        5. Batch upsert embeddings.

    Returns:
        Number of embedding rows processed.
    """

    if batch_size <= 0:
        raise ValueError(
            "batch_size must be greater than 0"
        )

    logger.info(
        "Starting job embedding ingestion."
    )

    logger.info(
        "Model: %s",
        model_name,
    )

    logger.info(
        "Chunk size: %d",
        chunk_size,
    )

    logger.info(
        "Chunk overlap: %d",
        chunk_overlap,
    )

    logger.info(
        "Batch size: %d",
        batch_size,
    )

    # This job can run standalone (e.g. via a scheduled job runner),
    # independently of whether the main app has ever been started -- it
    # must not assume the tables already exist. Idempotent: safe even if
    # the app's own ensure_job_schema() call already created everything.
    ensure_job_schema()

    total_written = 0

    with get_connection() as conn:

        # ---------------------------------------------------------------
        # 1. Fetch documents
        # ---------------------------------------------------------------

        with conn.cursor() as cur:
            documents = fetch_unembedded_documents(cur)

        # ---------------------------------------------------------------
        # 2. Deduplicate documents
        # ---------------------------------------------------------------
        #
        # This prevents duplicate:
        #
        #     (document_id, chunk_index)
        #
        # values from being generated inside the same execute_values()
        # statement.
        #
        # PostgreSQL raises:
        #
        #     CardinalityViolation:
        #     ON CONFLICT DO UPDATE command cannot affect row a second time
        #
        # when the same constrained key appears more than once in one
        # INSERT statement.
        #

        seen_ids = set()

        deduplicated = []

        duplicates_found = 0

        for doc in documents:

            doc_id = doc["id"]

            if doc_id not in seen_ids:

                seen_ids.add(doc_id)

                deduplicated.append(doc)

            else:

                duplicates_found += 1

                logger.warning(
                    "Skipping duplicate document_id in fetch result: %s",
                    doc_id,
                )

        documents = deduplicated

        if duplicates_found > 0:

            logger.warning(
                "Found %d duplicate document(s) in fetch result. "
                "This may indicate a data integrity issue in "
                "job_documents.",
                duplicates_found,
            )

        logger.info(
            "Found %d unique document(s) needing embeddings.",
            len(documents),
        )

        if not documents:

            logger.info(
                "No documents require embedding."
            )

            return 0

        # ---------------------------------------------------------------
        # 3. Chunk + embed
        # ---------------------------------------------------------------

        rows_to_write = []

        for doc in documents:

            document_id = doc["id"]

            source_type = doc["source_type"]

            description_text = doc["description_text"]

            content_hash = doc["content_hash"]

            chunks = chunk_text(
                description_text,
                chunk_size=chunk_size,
                overlap=chunk_overlap,
            )

            if not chunks:
                continue

            logger.info(
                "Document %s: %d chunk(s)",
                document_id,
                len(chunks),
            )

            vectors = embed_chunks(
                chunks,
                model_name=model_name,
            )

            # -----------------------------------------------------------
            # 4. Build database rows
            # -----------------------------------------------------------
            #
            # IMPORTANT:
            #
            # We DO NOT generate:
            #
            #     f"{document_id}#{chunk_index}"
            #
            # for job_embeddings.id.
            #
            # job_embeddings.id is BIGINT and is generated by
            # PostgreSQL.
            #
            # document_id is the TEXT FK.
            #

            for chunk_index, (chunk, vector) in enumerate(
                zip(chunks, vectors)
            ):

                rows_to_write.append(
                    (
                        document_id,
                        source_type,
                        chunk_index,
                        chunk,
                        content_hash,
                        vector,
                        model_name,
                    )
                )

        logger.info(
            "Writing %d embedding row(s).",
            len(rows_to_write),
        )

        if not rows_to_write:

            logger.info(
                "No embedding rows were generated."
            )

            return 0

        # ---------------------------------------------------------------
        # 5. Final safety check for duplicate conflict keys
        # ---------------------------------------------------------------
        #
        # This is an additional protection.
        #
        # The primary deduplication happens at document level above.
        # This second check ensures that the exact conflict key:
        #
        #     (document_id, chunk_index)
        #
        # is unique before sending the batch to PostgreSQL.
        #

        unique_rows = []

        seen_conflict_keys = set()

        duplicate_rows_found = 0

        for row in rows_to_write:

            conflict_key = (
                row[0],  # document_id
                row[2],  # chunk_index
            )

            if conflict_key not in seen_conflict_keys:

                seen_conflict_keys.add(
                    conflict_key
                )

                unique_rows.append(row)

            else:

                duplicate_rows_found += 1

                logger.warning(
                    "Skipping duplicate embedding key: "
                    "document_id=%s, chunk_index=%s",
                    row[0],
                    row[2],
                )

        rows_to_write = unique_rows

        if duplicate_rows_found > 0:

            logger.warning(
                "Removed %d duplicate embedding row(s) "
                "before database write.",
                duplicate_rows_found,
            )

        logger.info(
            "Final embedding row count to write: %d",
            len(rows_to_write),
        )

        # ---------------------------------------------------------------
        # 6. Batch upsert
        # ---------------------------------------------------------------

        with conn.cursor() as cur:

            for start in range(
                0,
                len(rows_to_write),
                batch_size,
            ):

                batch = rows_to_write[
                    start:start + batch_size
                ]

                cur.executemany(
                    UPSERT_EMBEDDINGS_SQL,
                    batch,
                )

                total_written += len(batch)

                logger.info(
                    "Wrote batch of %d "
                    "(running total: %d)",
                    len(batch),
                    total_written,
                )

        # Explicitly commit the transaction.

        conn.commit()

    logger.info(
        "Embedding ingestion completed successfully. "
        "Processed %d embedding row(s).",
        total_written,
    )

    return total_written


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    # Validate dependencies early
    try:
        import sentence_transformers
    except ImportError as e:
        raise ImportError(
            "sentence-transformers package not found. "
            "Install it with: pip install sentence-transformers"
        ) from e

    try:
        import psycopg2
    except ImportError as e:
        raise ImportError(
            "psycopg2 package not found. "
            "Install it with: pip install psycopg2-binary"
        ) from e

    parser = argparse.ArgumentParser(
        description=(
            "Generate job document embeddings "
            "and store them in Lakebase."
        )
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=(
            "Number of rows written per batch. "
            f"Default: {DEFAULT_BATCH_SIZE}"
        ),
    )

    parser.add_argument(
        "--embedding-model",
        default=DEFAULT_MODEL_NAME,
        help=(
            "SentenceTransformer model. "
            f"Default: {DEFAULT_MODEL_NAME}"
        ),
    )

    parser.add_argument(
        "--chunk-size",
        type=int,
        default=DEFAULT_CHUNK_SIZE,
        help=(
            "Chunk size in characters. "
            f"Default: {DEFAULT_CHUNK_SIZE}"
        ),
    )

    parser.add_argument(
        "--chunk-overlap",
        type=int,
        default=DEFAULT_CHUNK_OVERLAP,
        help=(
            "Chunk overlap in characters. "
            f"Default: {DEFAULT_CHUNK_OVERLAP}"
        ),
    )

    args = parser.parse_args()

    try:
        total = run(
            batch_size=args.batch_size,
            model_name=args.embedding_model,
            chunk_size=args.chunk_size,
            chunk_overlap=args.chunk_overlap,
        )
        logger.info("Job completed successfully. Total embeddings processed: %d", total)
    except psycopg2.Error as e:
        logger.error("Database error: %s", e)
        raise
    except Exception as e:
        logger.error("Unexpected error: %s", e, exc_info=True)
        raise


if __name__ == "__main__":
    main()
